# Generated by Django 4.2.11 on 2024-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
