# Generated by Django 4.2.11 on 2024-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='start_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='start_bid',
            field=models.IntegerField(null=True),
        ),
    ]
