# Generated by Django 4.1.7 on 2023-05-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_category_category_name_remove_listing_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
