# Generated by Django 4.2.11 on 2025-02-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_bid_remove_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_status',
        ),
    ]
