# Generated by Django 4.1.7 on 2023-05-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_comment_comment_name_alter_listing_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comment',
        ),
    ]
