# Generated by Django 4.1.7 on 2023-05-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category_category_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choices',
        ),
    ]
