# Generated by Django 4.1.7 on 2023-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_category_category_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(null=True, to='auctions.comment'),
        ),
    ]
