# Generated by Django 4.1.7 on 2023-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_comment_listing_listing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(to='auctions.comment'),
        ),
    ]
