# Generated by Django 4.2.11 on 2025-02-06 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_bid_listing_bid_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Auction',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listings',
            new_name='auction',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auction'),
            preserve_default=False,
        ),
    ]
