# Generated by Django 4.1.7 on 2023-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_category_options_remove_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
