# Generated by Django 4.2.11 on 2025-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.auction'),
        ),
    ]
