# Generated by Django 4.1.7 on 2023-05-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listing_comment_alter_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
