# Generated by Django 4.2.11 on 2025-02-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_rename_auction_watchlist_auctions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_status',
        ),
    ]
