# Generated by Django 4.1.7 on 2023-05-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_listing_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
        migrations.AddField(
            model_name='category',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='auctions.listing'),
        ),
    ]
