# Generated by Django 4.1.7 on 2023-05-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_category_listing_category_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listing',
            field=models.ManyToManyField(related_name='categories', to='auctions.listing'),
        ),
    ]
