# Generated by Django 4.1.7 on 2023-05-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_category_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='auctions.category'),
        ),
    ]
